<?php

declare(strict_types=1);

namespace Flytachi\Winter\Ppa\Mapping\Attributes\Hybrid;

use Attribute;
use Flytachi\Winter\Ppa\Mapping\Attributes\Additive\NullableIs;
use Flytachi\Winter\Ppa\Mapping\Attributes\Idx\Primary;
use Flytachi\Winter\Ppa\Mapping\Attributes\Primal\BigInteger;
use Flytachi\Winter\Ppa\Mapping\Attributes\Sub\AutoIncrement;

#[Attribute(Attribute::TARGET_PROPERTY)]
/**
 * @link https://winterframe.net/docs/entities Entities: primary keys
 */
final readonly class BigId implements AttributeDbHybrid
{
    /**
     * AutoIncrement attribute for marking a property as an auto-incrementing column.
     *
     * @param bool $always
     *     If true, uses `GENERATED ALWAYS AS IDENTITY` for Postgres.
     *     If false (default), uses `GENERATED BY DEFAULT AS IDENTITY` for Postgres.
     *     Has no effect for MySQL (always uses AUTO_INCREMENT).
     */
    public function __construct(
        private bool $always = false
    ) {
    }

    public function getInstances(string $dialect = 'mysql'): array
    {
        return [
            new Primary(),
            new AutoIncrement($this->always),
            new NullableIs(false),
            new BigInteger()
        ];
    }
}
