<?php

declare(strict_types=1);

namespace Flytachi\Winter\Ppa\Tests\Mapping\Attributes\Sub;

use Flytachi\Winter\Ppa\Mapping\Attributes\Sub\AutoIncrement;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;

final class AutoIncrementTest extends TestCase
{
    // ── supports() ───────────────────────────────────────────────────────────

    public function test_supports_only_int_or_mixed(): void
    {
        $ai = new AutoIncrement();
        $intTypes = ['int'];
        self::assertTrue($ai->supports($intTypes));

        $mixed = ['mixed'];
        self::assertTrue($ai->supports($mixed));

        $intNull = ['int', 'null'];
        self::assertTrue($ai->supports($intNull));

        $str = ['string'];
        self::assertFalse($ai->supports($str));
    }

    public function test_supports_strips_null_byref(): void
    {
        $types = ['int', 'null'];
        (new AutoIncrement())->supports($types);
        self::assertSame(['int'], array_values($types));
    }

    // ── toSql() per dialect ──────────────────────────────────────────────────

    /** @return array<string, array{0: string}> */
    public static function allowedTypes(): array
    {
        return [
            'INT'      => ['INT'],
            'BIGINT'   => ['BIGINT'],
            'SMALLINT' => ['SMALLINT'],
        ];
    }

    #[DataProvider('allowedTypes')]
    public function test_mysql_appends_auto_increment(string $type): void
    {
        self::assertSame("{$type} AUTO_INCREMENT", (new AutoIncrement())->toSql($type, 'mysql'));
    }

    #[DataProvider('allowedTypes')]
    public function test_pgsql_default_uses_generated_by_default(string $type): void
    {
        $ai = new AutoIncrement();
        self::assertSame(
            "{$type} GENERATED BY DEFAULT AS IDENTITY",
            $ai->toSql($type, 'pgsql'),
        );
    }

    #[DataProvider('allowedTypes')]
    public function test_pgsql_always_flag_uses_generated_always(string $type): void
    {
        $ai = new AutoIncrement(always: true);
        self::assertSame(
            "{$type} GENERATED ALWAYS AS IDENTITY",
            $ai->toSql($type, 'pgsql'),
        );
    }

    public function test_mysql_always_flag_has_no_effect(): void
    {
        // Per the docblock — `always` is pgsql-only.
        self::assertSame(
            'INT AUTO_INCREMENT',
            (new AutoIncrement(always: true))->toSql('INT', 'mysql'),
        );
    }

    public function test_invalid_type_throws(): void
    {
        $this->expectException(\RuntimeException::class);
        $this->expectExceptionMessage('AutoIncrement invalid type VARCHAR(255)');
        (new AutoIncrement())->toSql('VARCHAR(255)', 'mysql');
    }
}
