<?php

declare(strict_types=1);

namespace Flytachi\Winter\Ppa\Mapping\Attributes\Sub;

use Attribute;

#[Attribute(Attribute::TARGET_PROPERTY)]
/**
 * @link https://winterframe.net/docs/entities Entities: type modifiers
 */
final readonly class AutoIncrement implements AttributeDbSubType
{
    /**
     * AutoIncrement attribute for marking a property as an auto-incrementing column.
     *
     * @param bool $always
     *     If true, uses `GENERATED ALWAYS AS IDENTITY` for Postgres.
     *     If false (default), uses `GENERATED BY DEFAULT AS IDENTITY` for Postgres.
     *     Has no effect for MySQL (always uses AUTO_INCREMENT).
     */
    public function __construct(
        private bool $always = false
    ) {
    }

    public function supports(array &$phpTypes): bool
    {
        $phpTypes = array_filter($phpTypes, fn($type) => $type !== 'null');
        if (
            count($phpTypes) === 1
            && in_array($phpTypes[0], ['mixed', 'int'])
        ) {
            return true;
        }
        return false;
    }

    public function toSql(string $type, string $dialect = 'mysql'): string
    {
        if (!in_array($type, ['BIGINT', 'INT', 'SMALLINT'])) {
            throw new \RuntimeException(
                'AutoIncrement invalid type ' . $type
            );
        }
        return match ($dialect) {
            'pgsql' => $type . ($this->always
                ? ' GENERATED ALWAYS AS IDENTITY'
                : ' GENERATED BY DEFAULT AS IDENTITY'
            ),
            // SQLite auto-increments through the rowid alias, and a column only
            // becomes one when its type is spelled exactly INTEGER — INT, BIGINT and
            // SMALLINT are ordinary columns that would reject the omitted value with
            // a NOT NULL violation. There is one integer width anyway (64-bit), so
            // widening the declared type loses nothing. The AUTOINCREMENT keyword is
            // deliberately not emitted: it only forbids reusing ids after a delete,
            // at the cost of an extra bookkeeping table.
            'sqlite' => 'INTEGER',
            default => $type . ' AUTO_INCREMENT',
        };
    }
}
